version: '3.4'
networks:
  kurkuma-network:
    external: true

services:
  healthy-studio-api:
    extends:
      file: docker-compose.base.yml
      service: healthy-studio-api
    build:
      dockerfile: docker/configs/healthy-studio-api/Dockerfile.prod
    environment:
      NODE_ENV: prod
    image: ${DOCKER_PREFIX}:healthy-studio-api
    container_name: healthy-studio-api
    command: node index.js
