const HEALTH_DISK_THRESHOLD_PERCENT = 0.85;
const HEALTH_MEM_HEAP_THRESHOLD = 1024 ** 3;
const HEALTH_MEM_RSS_THRESHOLD = 1024 ** 3;
const LOCALHOST_URL = 'http://127.0.0.1';

export {
    HEALTH_DISK_THRESHOLD_PERCENT,
    HEALTH_MEM_HEAP_THRESHOLD,
    HEALTH_MEM_RSS_THRESHOLD,
    LOCALHOST_URL
};
