const FILE_NAME_ALLOWED_CHARS = 'a-zA-Z_0-9';
const PATH_ALLOWED_CHARS = `:\\/\\\\.\\-${FILE_NAME_ALLOWED_CHARS}`;
const FILE_NAME_MAX_LENGTH = 400;
const FILE_NAME_REGEX = new RegExp(`[${FILE_NAME_ALLOWED_CHARS}]+`);
const PATH_REGEX = new RegExp(`^[${PATH_ALLOWED_CHARS}]+$`);

export {
    FILE_NAME_ALLOWED_CHARS,
    PATH_ALLOWED_CHARS,
    FILE_NAME_MAX_LENGTH,
    FILE_NAME_REGEX,
    PATH_REGEX
};
